name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Dependencies
        run: |
          python -m venv .venv
          source .vevn/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Create a Django project and configure settings
        run: |
          source .vevn/bin/activate
          python -m django startproject mysite
          mv al_souk mysite
          cd mysite
          echo "AUTH_USER_MODEL = 'users.User'" >> mysite/settings.py
          echo "INSTALLED_APPS += ['al_souk', 'al_souk.categories', 'al_souk.items', 'al_souk.orders', 'al_souk.products', 'al_souk.reports', 'al_souk.reviews', 'al_souk.tags', 'al_souk.users', 'rest_framework']" >> mysite/settings.py
          echo "from django.urls import include" >> mysite/urls.py
          echo "urlpatterns += [path('', include('al_souk.urls'))]" >> mysite/urls.py

      - name: Run Migrations, System checks and test
        run: |
          source .vevn/bin/activate
          cd mysite
          python manage.py makemigrations
          python manage.py migrate
          python manage.py check
          python manage.py test
