name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Dependencies
        run: |
          python -m venv .venv
          source .vevn/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Create a Django project and configure settings
        run: |
          source .vevn/bin/activate
          python -m django startproject mysite
          mv souk_al_furqan mysite
          cd mysite
          echo "AUTH_USER_MODEL = 'users.User'" >> mysite/settings.py
          echo "INSTALLED_APPS += ['souk_al_fuqan', 'souk_al_furqan.categories', 'souk_al_furqan.items', 'souk_al_fuqan.orders', 'souk_al_fuqan.products', 'souk_al_fuqan.reports', 'souk_al_furqan.reviews', 'souk_al_fuqan.tags', 'souk_al_fuqan.users', 'rest_framework']" >> mysite/settings.py
          echo "from django.urls import include" >> mysite/urls.py
          echo "urlpatterns += [path('', include('souk_al_fuqan.urls'))]" >> mysite/urls.py

      - name: Run Migrations, System checks and test
        run: |
          source .vevn/bin/activate
          cd mysite
          python manage.py makemigrations
          python manage.py migrate
          python manage.py check
          python manage.py test
