name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Clone e_commerce
        run: |
          git clone https://github.com/youzarsiph/e-commerce
          mv e-commerce e_commerce
          
      - name: Install Dependencies
        run: |
          cp e_commerce/requirements.txt requirements.txt
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Create a Django project and configure settings
        run: |
          python -m django startproject mysite
          cp -r e_commerce mysite/e_commerce
          cd mysite
          echo "INSTALLED_APPS += ['e_commerce', 'e_commerce.categories', 'e_commerce.items', 'e_commerce.orders', 'e_commerce.products', 'e_commerce.reports', 'e_commerce.reviews', 'e_commerce.tags', 'rest_framework']" >> mysite/settings.py

      - name: Configure URLConf
        run: |
          cd mysite
          echo "from django.urls import include" >> mysite/urls.py
          echo "urlpatterns += [path('', include('e_commerce.urls'))]" >> mysite/urls.py

      - name: Run Migrations, System checks and test
        run: |
          cd mysite
          python manage.py migrate
          python manage.py check
          python manage.py test
